SET referential_integrity false;

DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders
             (
                          id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          user_id INTEGER NOT NULL CHECK (user_id>=0),
                          order_type    VARCHAR(50),
                          coin_type     VARCHAR(50),
                          order_quantity DECIMAL(19,2),
                          price          DECIMAL(19,2),
                          order_date_time TIMESTAMP,
                          deleted        BOOLEAN,
                          PRIMARY KEY (id)
             );

SET referential_integrity true;

INSERT INTO orders
            (
                        user_id,
                        order_type,
                        coin_type,
                        order_quantity,
                        price,
                        order_date_time,
                        deleted
            )
            VALUES
            (
                        1,
                        'SELL',
                        'ETH',
                        350.1,
                        13.06,
                        CURRENT_TIMESTAMP(),
                        false
            );

INSERT INTO orders
            (
                        user_id,
                        order_type,
                        coin_type,
                        order_quantity,
                        price,
                        order_date_time,
                        deleted
            )
            VALUES
            (
                        2,
                        'SELL',
                        'ETH',
                        50.5,
                        14.00,
                        CURRENT_TIMESTAMP(),
                        false
            );


INSERT INTO orders
            (
                        user_id,
                        order_type,
                        coin_type,
                        order_quantity,
                        price,
                        order_date_time,
                        deleted
            )
            VALUES
            (
                        3,
                        'SELL',
                        'ETH',
                        441.8,
                        13.90,
                        CURRENT_TIMESTAMP(),
                        false
            );

INSERT INTO orders
            (
                        user_id,
                        order_type,
                        coin_type,
                        order_quantity,
                        price,
                        order_date_time,
                        deleted
            )
            VALUES
            (
                        4,
                        'SELL',
                        'ETH',
                        3.5,
                        13.06,
                        CURRENT_TIMESTAMP(),
                        false
            );